# Generated by Django 3.2.8 on 2021-10-29 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relation', '0003_alter_phone_phone_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fkey', models.ManyToManyField(related_name='songname', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
