# Generated by Django 3.2.8 on 2021-10-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0006_usersongs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSongs',
        ),
    ]
